name: Branch

on:
  push:
    branches:
     - feat/*
  workflow_dispatch:

jobs:
  besu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=chainstep/go-ipfs:latest
          cache-to: type=inline
          tags: |
            chainstep/go-ipfs:0.8.0